# -*- coding: utf-8 -*-
"""Authored per-task detail. Authorized-lab context only.
Each id -> {why, how[], tools[], resources[{name,url?}], doneWhen, pitfall}
"""
import json

def R(*items):
    out = []
    for it in items:
        if isinstance(it, tuple):
            out.append({"name": it[0], "url": it[1]})
        else:
            out.append({"name": it})
    return out

DETAILS = {
# ============================== PHASE 1 ==============================
"P1-01": {
 "why": "Every AD attack, priv-esc, and evasion technique is a consequence of Windows primitives. If you can't reason about tokens, integrity levels, and LSASS, you're running tools you don't understand and can't troubleshoot when they fail.",
 "how": [
  "Read the process/thread/handle model, then observe it live with Process Hacker / System Informer on a lab VM.",
  "Study access tokens: primary vs impersonation, SIDs, privileges, integrity levels (Low/Medium/High/System) and how UAC splits an admin token.",
  "Map DPAPI (user vs machine master keys) and where secrets live (Credential Manager, browser data, LSASS).",
  "Understand LSASS's role in caching credentials and why it is the credential-access crown jewel; understand PPL as a protection on it.",
  "Write a one-page cheat-sheet in your own words linking each primitive to an attack it enables (e.g., SeImpersonate -> potato attacks).",
 ],
 "tools": ["Process Hacker / System Informer", "Sysinternals (Process Explorer, Handle, AccessChk)", "WinDbg (intro)", "whoami /all"],
 "resources": R(("Windows Internals (Russinovich) - reference", None), ("ired.team - Windows primitives", "https://www.ired.team"), ("HackTricks - Windows local privilege escalation", "https://book.hacktricks.xyz")),
 "doneWhen": "You can whiteboard, from memory, how UAC produces two tokens for an admin and name three attacks that abuse token/impersonation privileges.",
 "pitfall": "Memorising attack commands without the primitive underneath - you'll be lost the moment a lab deviates from the walkthrough.",
},
"P1-02": {
 "why": "You cannot evade or be detection-aware about telemetry you can't name. Knowing what Security/Sysmon/ETW/AMSI actually emit is the seed of every later evasion and every detection you'll write.",
 "how": [
  "Enumerate the key Security event IDs (4624/4625 logon, 4672 special privileges, 4688 process create, 4768/4769 Kerberos).",
  "Install Sysmon and read its event schema (process create=1, network=3, image load=7, CreateRemoteThread=8, etc.).",
  "Learn what ETW is and which providers matter (Microsoft-Windows-Threat-Intelligence, .NET, PowerShell).",
  "Understand AMSI as an in-memory scanning interface and WLDP/AppLocker as policy layers.",
  "Build a table: technique -> the telemetry it produces -> the log source that captures it.",
 ],
 "tools": ["Sysmon", "Windows Event Viewer", "ETW (logman, PerfView)", "Get-WinEvent (PowerShell)"],
 "resources": R(("Sysmon documentation (Microsoft Learn)", "https://learn.microsoft.com/sysinternals/downloads/sysmon"), ("SwiftOnSecurity sysmon-config", "https://github.com/SwiftOnSecurity/sysmon-config"), ("MITRE ATT&CK - Data Sources", "https://attack.mitre.org")),
 "doneWhen": "You can point at any Phase-2 technique and name the exact event ID(s) / ETW provider that would reveal it.",
 "pitfall": "Treating telemetry as 'the blue team's problem' - the operators who last are the ones who reason about signal before acting.",
},
"P1-03": {
 "why": "PowerShell and .NET are the native tooling language of Windows offense. You must be able to READ and WRITE tooling, not just paste one-liners, or you'll stall the first time a public script is signatured.",
 "how": [
  "Work through PowerShell scripting: functions, modules, objects/pipeline, error handling, remoting.",
  "Learn to call .NET classes directly from PowerShell ([System.Net...], reflection).",
  "Read the source of a real offensive module (e.g. PowerView) and explain what each function does.",
  "Write a small module of your own (e.g. an LDAP query helper) with parameters and help.",
  "Practice Add-Type to compile C# inline from PowerShell.",
 ],
 "tools": ["PowerShell 7 + Windows PowerShell 5.1", "VS Code + PowerShell extension", "PowerView (read the source)"],
 "resources": R(("Microsoft Learn - PowerShell", "https://learn.microsoft.com/powershell/"), ("PowerShell for Pentesters (various)", None)),
 "doneWhen": "You wrote a parameterised PowerShell module (not a one-liner) that queries AD via LDAP and returns objects.",
 "pitfall": "Copy-pasting encoded one-liners you can't reconstruct from scratch - it looks like skill but collapses under AV/EDR pressure.",
},
"P1-04": {
 "why": "This is the hard gate for Phase 3. Custom loaders, injection, and syscall work are written in C#/C. Without pointer/struct/calling-convention literacy you cannot build tooling and will be stuck at public PoCs forever.",
 "how": [
  "Learn C fundamentals: pointers, memory layout, structs, stack vs heap, function pointers, calling conventions (stdcall/fastcall).",
  "Learn enough C# to read offensive tooling: P/Invoke, DllImport, Marshal, unsafe/fixed, delegates.",
  "Re-implement a tiny C program (e.g. read another process's memory via ReadProcessMemory) to feel the Win32 API surface.",
  "Compile both a C and a C# console app and inspect them with a PE viewer.",
  "Keep a personal reference of the Win32 structs you'll reuse (STARTUPINFO, PROCESS_INFORMATION, etc.).",
 ],
 "tools": ["Visual Studio / VS Code", "gcc/clang or MSVC", "PE-bear / CFF Explorer", "pinvoke.net (reference)"],
 "resources": R(("pinvoke.net", "https://www.pinvoke.net"), ("Microsoft Learn - Win32 API", "https://learn.microsoft.com/windows/win32/api/"), ("ired.team - offensive C#", "https://www.ired.team")),
 "doneWhen": "You can read a P/Invoke signature and explain every marshaling attribute, and you compiled both a C and a C# tool that call a Win32 API.",
 "pitfall": "Skipping C 'because C# is enough' - syscalls, structs, and shellcode all assume you can think in memory.",
},
"P1-05": {
 "why": "AD is the enterprise attack graph. Done shallowly you memorise attack names; done properly you understand trusts, Kerberos, and LDAP well enough to see paths others miss.",
 "how": [
  "Diagram domain/forest/OU structure and the two trust directions (intra- vs inter-forest).",
  "Study Kerberos (AS-REQ/REP, TGS-REQ/REP, PAC) vs NTLM challenge/response - draw both flows.",
  "Learn LDAP query syntax and the key attributes (servicePrincipalName, userAccountControl, msDS-AllowedToActOnBehalfOfOtherIdentity).",
  "Understand GPO processing order and where it can be abused.",
  "Explain, in English, how a normal user logon becomes a TGT and then a service ticket.",
 ],
 "tools": ["AD DS lab role", "ldapsearch / Get-ADObject", "Active Directory Explorer (Sysinternals)"],
 "resources": R(("ADSecurity.org", "https://adsecurity.org"), ("The Hacker Recipes - Active Directory", "https://www.thehacker.recipes"), ("Microsoft Learn - AD DS", "https://learn.microsoft.com")),
 "doneWhen": "You can draw the full Kerberos ticket exchange and label where roasting, delegation, and PtT each attach.",
 "pitfall": "Learning 'Kerberoasting' as a command before understanding the SPN/TGS mechanism it abuses.",
},
"P1-06": {
 "why": "Every later phase needs a repeatable, snapshot-able lab. Your 16GB box is RAM-tight, so learning to build a minimal, resettable lab is itself a skill that protects the rest of the roadmap.",
 "how": [
  "Choose a hypervisor (Proxmox/ESXi/Hyper-V; VMware Workstation is fine) and enable snapshots.",
  "Build a DC + 1-2 Windows clients + one Linux box; keep memory small (2-4GB each) and snapshot clean states.",
  "Automate rebuilds with Ludus or scripted installs so you can reset in minutes, not hours.",
  "Document a 'clean baseline' snapshot you return to before every exercise.",
  "Confirm you can suspend the whole lab to free RAM for other work.",
 ],
 "tools": ["Proxmox / VMware / Hyper-V", "Ludus", "Windows Server + client eval ISOs", "Ubuntu/Debian"],
 "resources": R(("Ludus", "https://ludus.cloud"), ("GOAD (lab framework)", "https://github.com/Orange-Cyberdefense/GOAD")),
 "doneWhen": "You can revert the entire lab to a clean snapshot in under 5 minutes and it boots cleanly.",
 "pitfall": "Building one giant fragile lab with no snapshots - you'll fear breaking it and stop experimenting.",
},
"P1-07": {
 "why": "Watching your own attacks from day one is the single habit that makes you detection-aware. If your SIEM shows what you did, you'll never again 'get a shell' with no idea of the noise you made.",
 "how": [
  "Install Sysmon with the SwiftOnSecurity config on every Windows host.",
  "Stand up a SIEM (Wazuh or a single-node Elastic) and ship Windows Security + Sysmon logs to it.",
  "Verify ingestion by generating a test event and finding it in the SIEM.",
  "Build a couple of saved searches / dashboards for logons and process creation.",
  "Snapshot the working state so you can always return to a functioning SIEM.",
 ],
 "tools": ["Sysmon", "Wazuh or Elastic (Elasticsearch+Kibana)", "Winlogbeat/Elastic Agent", "SwiftOnSecurity config"],
 "resources": R(("Wazuh docs", "https://documentation.wazuh.com"), ("Elastic - ingest Windows logs", "https://www.elastic.co/guide"), ("SwiftOnSecurity sysmon-config", "https://github.com/SwiftOnSecurity/sysmon-config")),
 "doneWhen": "You run a benign action on a lab host and find the corresponding Sysmon/Security event in your SIEM within a minute.",
 "pitfall": "Deploying the SIEM but never actually reading it during exercises - instrumentation you ignore teaches you nothing.",
},
"P1-08": {
 "why": "GOAD is a free, misconfig-rich AD lab. Mapping it with BloodHound and explaining every edge trains graph-thinking - the core skill that separates path-finders from tool-runners.",
 "how": [
  "Provision GOAD (or GOAD-Light to save RAM) and confirm all hosts are up.",
  "Collect with SharpHound and open the graph in BloodHound.",
  "For each edge type (MemberOf, AdminTo, GenericAll, etc.) explain in English what it means and how it could be abused.",
  "Identify at least two paths to Domain Admin and articulate which is quieter.",
  "Write a short note mapping edges to the Phase-2 techniques that exploit them.",
 ],
 "tools": ["GOAD", "SharpHound", "BloodHound (Community Edition)", "Neo4j"],
 "resources": R(("GOAD", "https://github.com/Orange-Cyberdefense/GOAD"), ("BloodHound CE", "https://github.com/SpecterOps/BloodHound"), ("The Hacker Recipes - AD", "https://www.thehacker.recipes")),
 "doneWhen": "You can walk a peer through two distinct DA paths in GOAD and justify which edges are noisier.",
 "pitfall": "Clicking 'shortest path to DA' and stopping - the edges you skip are exactly the ones you must be able to explain.",
},
"P1-09": {
 "why": "Manually manipulating tokens and integrity levels demystifies UAC and impersonation, the foundation of many local priv-esc primitives.",
 "how": [
  "Use whoami /all and Process Hacker to inspect a process token (SIDs, privileges, integrity).",
  "Compare a Medium-integrity vs High-integrity process side by side.",
  "Perform a manual UAC bypass technique in the lab and observe the integrity change.",
  "Diff the token before/after and write down exactly what changed.",
  "Correlate the action with what appears in your SIEM.",
 ],
 "tools": ["Process Hacker / System Informer", "whoami /all", "AccessChk", "incognito-style token tooling (lab)"],
 "resources": R(("HackTricks - integrity levels / UAC", "https://book.hacktricks.xyz"), ("ired.team - token manipulation", "https://www.ired.team")),
 "doneWhen": "You elevated integrity via a token/UAC technique in lab and produced a before/after token diff explaining the change.",
 "pitfall": "Running a UAC-bypass tool as a black box without confirming the integrity level actually changed.",
},
"P1-10": {
 "why": "AMSI is the in-memory scanning chokepoint you'll later learn to bypass. Triggering it and watching the event fire connects the offensive action to its telemetry.",
 "how": [
  "Feed a known AMSI test string (e.g. the standard AMSI test sample) into PowerShell and observe the block.",
  "Locate the corresponding event (Defender/Operational or ETW) in your SIEM.",
  "Repeat via a .NET assembly load to see AMSI's reach beyond PowerShell.",
  "Note exactly which provider/event captured it for your TTP notebook.",
 ],
 "tools": ["PowerShell", "Windows Defender", "Get-WinEvent", "your SIEM"],
 "resources": R(("Microsoft Learn - Antimalware Scan Interface (AMSI)", "https://learn.microsoft.com/windows/win32/amsi/"), ("MITRE ATT&CK - T1562.001", "https://attack.mitre.org")),
 "doneWhen": "You triggered AMSI and located the resulting event in your SIEM, recording the provider/event ID.",
 "pitfall": "Assuming AMSI only touches PowerShell - it also scans .NET, VBScript, and more.",
},
"P1-11": {
 "why": "Writing a P/Invoke tool proves you can call the Win32 API directly rather than leaning on managed wrappers - the exact skill Phase 3 tooling is built on.",
 "how": [
  "Define the P/Invoke signatures for a process-enumeration API (e.g. CreateToolhelp32Snapshot/Process32Next, or NtQuerySystemInformation).",
  "Marshal the returned structs correctly in C#.",
  "Print PID/name for every process WITHOUT using System.Diagnostics.Process.",
  "Compile and run; verify output matches Task Manager.",
  "Note which API you chose and why (telemetry differences).",
 ],
 "tools": ["Visual Studio / dotnet CLI", "pinvoke.net", "C#"],
 "resources": R(("pinvoke.net", "https://www.pinvoke.net"), ("Microsoft Learn - ToolHelp API", "https://learn.microsoft.com/windows/win32/toolhelp/")),
 "doneWhen": "Your compiled C# tool lists all processes via raw P/Invoke and its output matches the OS, with no System.Diagnostics.",
 "pitfall": "Getting struct sizes/marshaling wrong and silently reading garbage - validate against a known-good source.",
},
"P1-12": {
 "why": "This is a knowledge gate: if you can't explain Kerberos from memory, every Phase-2 ticket attack is cargo-culting. Being able to teach it is the proof you understand it.",
 "how": [
  "Whiteboard AS-REQ/AS-REP (TGT issuance) and TGS-REQ/TGS-REP (service ticket).",
  "Explain the PAC and why the KDC/service trust it.",
  "Attach each attack to its step: AS-REP roast (pre-auth off), Kerberoast (TGS for SPN), PtT (reuse ticket), Golden (forge TGT), Silver (forge TGS).",
  "Do it with no notes to a peer or camera.",
 ],
 "tools": ["Whiteboard/paper", "Wireshark (to watch real Kerberos in lab)"],
 "resources": R(("ADSecurity - Kerberos", "https://adsecurity.org"), ("The Hacker Recipes - Kerberos", "https://www.thehacker.recipes")),
 "doneWhen": "You explained the full TGT/TGS exchange and correctly placed 5 attacks on it, from memory.",
 "pitfall": "Confusing where Golden (TGT/krbtgt) vs Silver (TGS/service account) tickets are forged.",
},
"P1-13": {
 "why": "The combined gate proves the two Phase-1 disciplines are real: you can read your own telemetry AND build native tooling. Both are hard prerequisites for everything after.",
 "how": [
  "Run a benign multi-step action in lab and reconstruct it purely from your SIEM.",
  "Independently compile and run your P/Invoke tool on a fresh VM.",
  "Write a short paragraph mapping each action to the events it produced.",
 ],
 "tools": ["Your SIEM", "Visual Studio / dotnet", "Sysmon"],
 "resources": R(("Your Phase-1 notes", None)),
 "doneWhen": "Both sub-gates pass: you reconstructed an action from SIEM data and compiled your own tool unaided.",
 "pitfall": "Passing one half and hand-waving the other - the gate only counts if both are demonstrably true.",
},
# ============================== PHASE 2 ==============================
"P2-01": {
 "why": "Discovery is where every AD engagement really starts. BloodHound + LDAP recon turn a blind foothold into a map of who-can-reach-what, which is the whole game.",
 "how": [
  "Run SharpHound with appropriate collection methods and import into BloodHound.",
  "Enumerate users, groups, computers, GPOs, ACLs, and sessions via LDAP.",
  "Hunt for high-value targets: DA sessions, unconstrained delegation, dangerous ACLs.",
  "Use built-in and custom Cypher queries to find non-obvious paths.",
  "Correlate SharpHound's collection with what your SIEM logged (it is noisy).",
 ],
 "tools": ["SharpHound", "BloodHound CE", "PowerView/SharpView", "ldapsearch", "netexec (nxc)"],
 "resources": R(("BloodHound CE", "https://github.com/SpecterOps/BloodHound"), ("The Hacker Recipes - recon", "https://www.thehacker.recipes")),
 "doneWhen": "From a low-priv foothold in lab you produced a written target list (paths, delegations, dangerous ACLs) derived from your own collection.",
 "pitfall": "Over-collecting loudly with default SharpHound options when a targeted, quieter collection would do.",
},
"P2-02": {
 "why": "Credential access is the pivot fuel of AD. Understanding roasting, DCSync, and LSASS/DPAPI/SAM extraction (and their telemetry) is mandatory core tradecraft.",
 "how": [
  "Kerberoast SPN accounts and AS-REP roast pre-auth-disabled accounts; crack offline in lab.",
  "Perform DCSync with replication rights and understand exactly which right is required.",
  "Extract credential material from LSASS, SAM, and DPAPI in a lab host and understand each store.",
  "For each technique, capture the event it generated (4769, 4662, handle to lsass, etc.).",
  "Write the detection you'd expect the blue team to have.",
 ],
 "tools": ["Rubeus", "impacket (secretsdump, GetUserSPNs)", "mimikatz (for understanding)", "hashcat"],
 "resources": R(("The Hacker Recipes - credentials", "https://www.thehacker.recipes"), ("ADSecurity - DCSync/Kerberoast", "https://adsecurity.org"), ("MITRE ATT&CK - Credential Access", "https://attack.mitre.org")),
 "doneWhen": "You executed Kerberoast, AS-REP roast, and DCSync in lab and named the specific event each produced.",
 "pitfall": "Thinking DCSync needs Domain Admin - it needs specific replication rights, which is exactly why delegated ACLs matter.",
},
"P2-03": {
 "why": "ACL and delegation abuse are the quiet privilege-escalation edges BloodHound surfaces. RBCD and delegation variants are among the most reliable modern paths.",
 "how": [
  "Enumerate dangerous ACLs (GenericAll, WriteDACL, WriteOwner, ForceChangePassword) and abuse one end-to-end.",
  "Study unconstrained vs constrained delegation and Resource-Based Constrained Delegation (RBCD).",
  "Configure and abuse RBCD in lab (write msDS-AllowedToActOnBehalfOfOtherIdentity, then S4U).",
  "Abuse a GPO edge to gain execution.",
  "Record telemetry (4742 object modification, 4769 with S4U) for each.",
 ],
 "tools": ["PowerView", "Rubeus (S4U)", "impacket (rbcd.py)", "BloodHound", "Certipy (for ESC via ACL)"],
 "resources": R(("The Hacker Recipes - delegations", "https://www.thehacker.recipes"), ("ired.team - RBCD", "https://www.ired.team")),
 "doneWhen": "You escalated privileges in lab via an ACL edge AND an RBCD abuse, explaining the required rights for each.",
 "pitfall": "Confusing constrained vs RBCD prerequisites (who you need write access over) - the S4U flow differs.",
},
"P2-04": {
 "why": "AD Certificate Services misconfigurations (ESC1-ESC14) are current king-makers - many give domain compromise from a low-priv user. Know them cold.",
 "how": [
  "Enumerate the CA and templates with Certipy 'find'.",
  "Learn the ESC family: ESC1 (SAN abuse), ESC2, ESC3, ESC4 (template ACL), ESC6 (EDITF flag), ESC8 (NTLM relay to web enrollment), and the newer ESC9-ESC14.",
  "For each ESC in your lab CA, identify the misconfiguration that enables it.",
  "Map which ESC yields authentication-as-anyone vs CA control.",
  "Write remediation notes per ESC (template hardening, disable web enrollment, etc.).",
 ],
 "tools": ["Certipy", "Certify + ForgeCert", "PKINITtools", "BloodHound (cert edges)"],
 "resources": R(("Certipy", "https://github.com/ly4k/Certipy"), ("SpecterOps - Certified Pre-Owned (whitepaper)", "https://posts.specterops.io"), ("The Hacker Recipes - ADCS", "https://www.thehacker.recipes")),
 "doneWhen": "You can explain each major ESC's root misconfiguration and its fix without notes, and identified which apply to your lab CA.",
 "pitfall": "Learning only ESC1/ESC8 and stopping - assessors are increasingly finding ESC9-ESC14 and template ACL issues.",
},
"P2-05": {
 "why": "Lateral movement is how a single compromise becomes domain reach. Knowing the exec method families and their footprints lets you pick the quiet option.",
 "how": [
  "Practice PtH, overpass-the-hash, and PtT to authenticate laterally.",
  "Execute via WMI, WinRM, PsExec/SMB (service create), and DCOM - one at a time.",
  "For each method, record the artefacts (7045 service install, 4624 type 3, named pipe, WMI events).",
  "Rank the methods by noise and pick a default for a quiet op.",
  "Reproduce one method with impacket and one with a C2's built-in.",
 ],
 "tools": ["impacket (psexec/wmiexec/smbexec)", "Rubeus", "netexec (nxc)", "Evil-WinRM"],
 "resources": R(("The Hacker Recipes - lateral movement", "https://www.thehacker.recipes"), ("ired.team - lateral movement", "https://www.ired.team")),
 "doneWhen": "You moved laterally with four distinct exec methods in lab and produced a noise-ranked comparison.",
 "pitfall": "Defaulting to PsExec everywhere - the service-create + named-pipe pattern is one of the most heavily alerted behaviours.",
},
"P2-06": {
 "why": "Persistence and ticket forgery let you understand both durable access and the detections that catch it. Golden/Silver/Diamond tickets are core red-team knowledge.",
 "how": [
  "Forge a Golden ticket (krbtgt hash) and a Silver ticket (service account) in lab; note the difference.",
  "Study Diamond tickets (modifying a real TGT) vs Golden and why Diamond is stealthier.",
  "Abuse AdminSDHolder / DCSync rights as a persistence mechanism.",
  "Establish certificate-based persistence (a user/machine cert that survives password resets).",
  "Capture how each would appear (or not) in telemetry.",
 ],
 "tools": ["mimikatz / Rubeus", "impacket (ticketer)", "Certipy", "PowerView (AdminSDHolder)"],
 "resources": R(("ADSecurity - Golden/Silver tickets", "https://adsecurity.org"), ("The Hacker Recipes - persistence", "https://www.thehacker.recipes")),
 "doneWhen": "You forged Golden and Silver tickets in lab and can explain why a Diamond ticket is harder to detect than a Golden one.",
 "pitfall": "Believing forged tickets are invisible - anomalous ticket lifetimes and PAC inconsistencies are exactly what mature detections hunt.",
},
"P2-07": {
 "why": "Trust attacks turn one compromised domain into forest-wide (or cross-forest) reach. SID history and trust keys are the mechanisms behind the most impactful escalations.",
 "how": [
  "Diagram the trust directions and which SIDs cross them (SID filtering matters).",
  "Extract a trust key and forge an inter-realm TGT in lab.",
  "Abuse SID history to gain privileges across a trust.",
  "Distinguish intra-forest (implicitly trusted) from cross-forest (filtered) paths.",
  "Note the remediation (SID filtering, selective authentication).",
 ],
 "tools": ["mimikatz / Rubeus", "impacket", "BloodHound (cross-domain edges)"],
 "resources": R(("The Hacker Recipes - trusts", "https://www.thehacker.recipes"), ("ADSecurity - trusts", "https://adsecurity.org")),
 "doneWhen": "You performed a cross-domain compromise in lab via trust-key or SID-history abuse and explained SID filtering's effect.",
 "pitfall": "Assuming cross-forest works like intra-forest - SID filtering blocks many SID-history tricks across forest boundaries.",
},
"P2-08": {
 "why": "Running a full chain WHILE your SIEM records, then writing the detections, is the exercise that converts you from attacker to operator. It forces the detection-aware habit.",
 "how": [
  "Take an initial foothold in GOAD, Kerberoast to creds, traverse an ACL path, then DCSync.",
  "Keep Sysmon + Security logs flowing to your SIEM throughout.",
  "For each step, find the telemetry it produced.",
  "Write a Sigma rule (or SIEM query) that would have caught each step.",
  "Produce a one-page attack+detection writeup.",
 ],
 "tools": ["GOAD", "SharpHound/BloodHound", "Rubeus", "impacket", "Sigma", "your SIEM"],
 "resources": R(("Sigma rules", "https://github.com/SigmaHQ/sigma"), ("GOAD", "https://github.com/Orange-Cyberdefense/GOAD")),
 "doneWhen": "You have a writeup with, for every chain step, the observed event and a detection rule that fires on it.",
 "pitfall": "Doing the attack first and reconstructing detections from memory later - instrument BEFORE you start or you'll miss signals.",
},
"P2-09": {
 "why": "Dante is a broad, methodology-focused Pro Lab - a good warm-up to internalise a repeatable network-to-AD workflow before the harder AD sims.",
 "how": [
  "Approach it as an engagement: enumerate, foothold, loot, pivot, repeat.",
  "Keep structured notes (hosts, creds, pivots) as if writing a report.",
  "Tunnel between segments cleanly (ligolo-ng) rather than ad-hoc.",
  "Review your path afterwards for the quieter route you missed.",
 ],
 "tools": ["Hack The Box (Dante)", "ligolo-ng", "netexec", "standard enum tooling"],
 "resources": R(("Hack The Box Pro Labs", "https://www.hackthebox.com/hacker/pro-labs")),
 "doneWhen": "You owned every Dante flag and kept engagement-grade notes you could turn into a report.",
 "pitfall": "Chasing flags without notes - the value here is a repeatable methodology, not the flag count.",
},
"P2-10": {
 "why": "Zephyr is an intermediate AD red-team simulation full of realistic misconfigurations - the bridge between guided labs and unassisted assessment.",
 "how": [
  "Treat it as assumed-breach AD: map with BloodHound, then work paths to DA.",
  "Force yourself to use ADCS/delegation/ACL techniques, not just credential dumping.",
  "Maintain a path diagram as you go.",
  "After finishing, redo one path via a quieter technique.",
 ],
 "tools": ["Hack The Box (Zephyr)", "BloodHound", "Certipy", "Rubeus", "impacket"],
 "resources": R(("Hack The Box - Zephyr", "https://www.hackthebox.com/hacker/pro-labs")),
 "doneWhen": "You compromised Zephyr's objectives and produced a path diagram with remediation for each edge you used.",
 "pitfall": "Leaning on one technique class - Zephyr rewards breadth across ADCS, delegation, and ACLs.",
},
"P2-11": {
 "why": "Doing an ADCS ESC path end-to-end with Certipy turns abstract knowledge into a repeatable capability you can rely on under pressure.",
 "how": [
  "Enumerate templates with Certipy find and pick a vulnerable one (ESC1) or target web enrollment (ESC8).",
  "For ESC1: request a cert specifying an arbitrary SAN, then authenticate as that principal.",
  "For ESC8: coerce auth and relay to the CA web endpoint to obtain a cert.",
  "Use the cert to obtain a TGT / NT hash (PKINIT / UnPAC-the-hash).",
  "Document the exact misconfiguration and its fix.",
 ],
 "tools": ["Certipy", "PetitPotam/Coercer (ESC8)", "ntlmrelayx", "Rubeus"],
 "resources": R(("Certipy", "https://github.com/ly4k/Certipy"), ("The Hacker Recipes - ADCS", "https://www.thehacker.recipes")),
 "doneWhen": "You went from low-priv user to authenticating as a privileged principal via one ESC path, fully in lab.",
 "pitfall": "Skipping the enumeration step and guessing the ESC - Certipy find tells you exactly which templates are abusable.",
},
"P2-12": {
 "why": "Cross-forest compromise is a high-impact, frequently-tested skill that proves you understand trust mechanics rather than single-domain tricks.",
 "how": [
  "Build (or use GOAD's) two-forest setup with a trust.",
  "Enumerate the trust and foreign group memberships / ACLs.",
  "Abuse a trust path (trust key, foreign ACL, or ADCS across the trust).",
  "Reach a privileged principal in the target forest.",
  "Explain why SID filtering did or didn't stop you.",
 ],
 "tools": ["BloodHound", "Rubeus", "impacket", "Certipy"],
 "resources": R(("GOAD (multi-forest)", "https://github.com/Orange-Cyberdefense/GOAD"), ("The Hacker Recipes - trusts", "https://www.thehacker.recipes")),
 "doneWhen": "You compromised a principal in a second forest across a trust and explained the filtering behaviour you hit.",
 "pitfall": "Expecting intra-forest tricks to just work across a forest boundary - the security boundary is the forest, not the domain.",
},
"P2-13": {
 "why": "Doing a full lab with no Metasploit and no mimikatz easy-button forces you to understand mechanics, so you're not helpless when those tools are flagged or unavailable.",
 "how": [
  "Pick a lab you can already beat and re-run it with a self-imposed tool ban.",
  "Use Rubeus/Certipy/impacket and hand-built steps instead of one-click modules.",
  "When you reach for the banned tool, stop and learn the manual equivalent.",
  "Note every place the constraint exposed a knowledge gap.",
 ],
 "tools": ["Rubeus", "Certipy", "impacket", "netexec", "Evil-WinRM"],
 "resources": R(("impacket", "https://github.com/fortra/impacket"), ("Rubeus", "https://github.com/GhostPack/Rubeus")),
 "doneWhen": "You fully compromised a lab without Metasploit or mimikatz's convenience commands and listed the gaps it exposed.",
 "pitfall": "Cheating 'just once' on the hard step - that step is precisely the one you most need to learn.",
},
"P2-14": {
 "why": "Owning a fresh, unseen AD lab unassisted is the Phase-2 proof of independence. Walkthroughs teach recognition; unseen labs teach problem-solving under uncertainty.",
 "how": [
  "Pick an AD lab/box you have not seen and time-box it (no writeups).",
  "Work the full chain: recon -> foothold -> priv-esc -> lateral -> DA.",
  "Produce a path diagram and per-edge remediation.",
  "Write it up as a mini report.",
 ],
 "tools": ["Fresh AD lab (HTB/Altered Security)", "BloodHound", "your full Phase-2 toolkit"],
 "resources": R(("Hack The Box", "https://www.hackthebox.com"), ("Altered Security labs", "https://www.alteredsecurity.com")),
 "doneWhen": "You reached Domain Admin unassisted on an unseen lab and delivered a path diagram + remediation.",
 "pitfall": "Peeking at a writeup when stuck - it converts a real assessment into a guided one and hides the gap.",
},
"P2-15": {
 "why": "CRTP validates single-forest AD attack fluency and is the recognised entry milestone to red-team AD work. The exam is hands-on, which forces real skill.",
 "how": [
  "Work the Altered Security CRTP course lab fully, not just the videos.",
  "Practice enumeration, delegation, ACLs, trusts, and persistence until they're second nature.",
  "Do a timed dry-run compromise before booking.",
  "Sit the 24h hands-on exam and write the report.",
 ],
 "tools": ["Altered Security CRTP lab", "PowerView", "Rubeus", "your AD toolkit"],
 "resources": R(("Altered Security - CRTP", "https://www.alteredsecurity.com")),
 "doneWhen": "You hold the CRTP certification (exam passed and report accepted).",
 "pitfall": "Watching the course passively - the exam is practical, so lab reps, not video hours, are what pass it.",
},
# ============================== PHASE 3 ==============================
"P3-01": {
 "why": "C2 architecture and operation is the backbone of adversary emulation. Understanding listeners, profiles, redirectors, and sleep/jitter OPSEC is what lets you operate quietly in a defended network.",
 "how": [
  "Study the C2 model: listener, stager vs stageless, beacon, redirector, team server.",
  "Learn sleep/jitter and why cadence matters for network detection.",
  "Read a malleable/HTTP profile and understand how it shapes traffic.",
  "Design an egress plan (which ports/domains, how to blend in).",
  "Run a benign beacon in lab and observe its callback pattern in your SIEM.",
 ],
 "tools": ["Cobalt Strike / Sliver / Mythic", "redirectors (nginx/Apache)", "your SIEM", "Wireshark"],
 "resources": R(("The C2 Matrix", "https://www.thec