# -*- coding: utf-8 -*-
"""Per-task GUIDES for the Red Team Mastery Tracker — two variants per task.

BEGINNER[id] : gentle, assumes no background, names prerequisites, adds a
               safety reminder and a small first win. Shown in Beginner mode.
PRO[id]      : terse, assumes fluency, depth/OPSEC oriented. Shown in Pro mode
               for the tasks NOT already covered by details_data.DETAILS
               (Phase 1-2 + P3-01 come from DETAILS; everything else lives here).

Each entry: {overview, steps[], tools[], resources[{name,url?}], doneWhen, pitfall}
Authorized labs and environments only.
"""

def R(*items):
    out = []
    for it in items:
        if isinstance(it, tuple):
            out.append({"name": it[0], "url": it[1]})
        else:
            out.append({"name": it})
    return out

BEGINNER = {}
PRO = {}

# ============================== BEGINNER · PHASE 1 ==============================
BEGINNER.update({
"P1-01": {
 "overview": "Before any 'hacking', learn how Windows actually works underneath — processes, the tokens that carry your permissions, and where passwords live in memory. Everything later is a consequence of these basics.",
 "steps": [
  "Spin up ONE Windows VM you own. Never practise on a machine you don't control.",
  "Install System Informer (formerly Process Hacker) and just look: open a process, see its threads, its token, its integrity level.",
  "Run `whoami /all` in a terminal and read every line — those groups and privileges ARE your token.",
  "Watch a normal admin login: notice you get a 'medium' token until you 'Run as administrator' (that's UAC).",
  "Write a one-page note in plain English: what is a token, what is an integrity level, what is LSASS.",
 ],
 "tools": ["A Windows 10/11 VM", "System Informer / Process Hacker", "whoami /all", "Task Manager"],
 "resources": R(("HackTricks — Windows local privilege escalation", "https://book.hacktricks.xyz"), ("Microsoft — Access tokens", "https://learn.microsoft.com/windows/win32/secauthz/access-tokens")),
 "doneWhen": "You can explain, in your own words, what a token is and why 'Run as administrator' gives you a different one.",
 "pitfall": "Trying to memorise attack commands before you understand tokens — you'll be lost the first time a tutorial doesn't match your screen.",
},
"P1-02": {
 "overview": "Learn what Windows writes down when things happen — the logs and events. Knowing what leaves a trace makes you both a better attacker and a better defender.",
 "steps": [
  "Open Event Viewer on your VM and browse Security logs. Log in and out; watch events 4624 (logon) and 4625 (failed logon) appear.",
  "Install Sysmon with a starter config (SwiftOnSecurity) — it adds much richer logs.",
  "Do something ordinary (open Notepad) and find the 'process created' event it generated.",
  "Make a simple table: 'action I took' -> 'log it created'. Keep adding to it as you learn.",
 ],
 "tools": ["Event Viewer", "Sysmon", "SwiftOnSecurity sysmon-config", "Get-WinEvent"],
 "resources": R(("Sysmon docs", "https://learn.microsoft.com/sysinternals/downloads/sysmon"), ("SwiftOnSecurity config", "https://github.com/SwiftOnSecurity/sysmon-config")),
 "doneWhen": "You can open Event Viewer, log in, and point to the exact event that recorded it.",
 "pitfall": "Thinking logs are 'the defender's job' — the operators who last are the ones who know what they're leaving behind.",
},
"P1-03": {
 "overview": "PowerShell is the native language of Windows automation and offense. Get comfortable writing small scripts, not just pasting one-liners you don't understand.",
 "steps": [
  "Install VS Code + the PowerShell extension.",
  "Learn the basics: variables, if/foreach, functions, and how the pipeline passes objects (not text).",
  "Write a tiny function of your own that takes a parameter and returns something — e.g. list processes over 100MB.",
  "Read a real script (like PowerView) and try to explain what one function does.",
 ],
 "tools": ["PowerShell 7", "VS Code + PowerShell extension"],
 "resources": R(("Microsoft Learn — PowerShell", "https://learn.microsoft.com/powershell/")),
 "doneWhen": "You wrote your own small PowerShell function with a parameter and understand every line of it.",
 "pitfall": "Copy-pasting encoded one-liners you can't rebuild yourself — it feels like progress but collapses the moment antivirus flags it.",
},
"P1-04": {
 "overview": "A gentle first look at C# and C. You don't need to be a developer — you need to READ offensive tooling and understand pointers and memory. This is the gate to the later custom-tooling phases.",
 "steps": [
  "Install Visual Studio Community (free). Create a C# console app that prints something — get the build/run loop working.",
  "Learn what a pointer is, conceptually: a variable that holds a memory address. Draw it on paper.",
  "Learn what P/Invoke means: calling a built-in Windows function from C#. Read one example on pinvoke.net.",
  "Don't rush. Understanding 'memory has addresses and functions live at addresses' is the real win here.",
 ],
 "tools": ["Visual Studio Community", "pinvoke.net (reference)"],
 "resources": R(("pinvoke.net", "https://www.pinvoke.net"), ("Microsoft Learn — C# fundamentals", "https://learn.microsoft.com/dotnet/csharp/")),
 "doneWhen": "You compiled and ran a C# console app and can explain in one sentence what a pointer is.",
 "pitfall": "Skipping this because it's 'programming, not hacking' — every custom loader in later phases is written in exactly this.",
},
"P1-05": {
 "overview": "Active Directory (AD) is how companies manage all their Windows computers and users. Almost every corporate red-team attack is really an AD attack, so learn the map before the moves.",
 "steps": [
  "Learn the words: domain, forest, domain controller (DC), user, group, GPO. Make a glossary.",
  "Understand at a high level how login works: Kerberos hands out 'tickets'. Draw the flow simply.",
  "Learn what LDAP is (the directory you query) and what a 'service account' is.",
  "You don't need a lab yet for this — just solid vocabulary and a mental model.",
 ],
 "tools": ["Diagrams on paper", "A note-taking app"],
 "resources": R(("HackTricks — Active Directory methodology", "https://book.hacktricks.xyz"), ("Microsoft — AD DS overview", "https://learn.microsoft.com/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview")),
 "doneWhen": "You can explain to a friend what a domain controller is and why Kerberos 'tickets' matter.",
 "pitfall": "Jumping to attack names (Kerberoast, DCSync) before you know what a ticket or a domain even is.",
},
"P1-06": {
 "overview": "Build your own safe practice lab: a few Windows VMs on your own computer that you can break and restore. This is where ALL your practice happens — never on real or other people's systems.",
 "steps": [
  "Install a hypervisor: VirtualBox (free) or VMware Workstation Player.",
  "Create one Windows Server VM (your Domain Controller) and one Windows 10/11 VM (a 'workstation').",
  "Take a SNAPSHOT of each once installed — this lets you undo any mess in seconds.",
  "Give them a private/host-only network so they talk to each other but stay isolated from your real network.",
 ],
 "tools": ["VirtualBox or VMware Workstation", "Windows eval ISOs (free 180-day)", "8GB+ RAM recommended"],
 "resources": R(("VirtualBox", "https://www.virtualbox.org"), ("Windows Server eval", "https://www.microsoft.com/evalcenter")),
 "doneWhen": "Two VMs boot, can ping each other on a private network, and you've taken restorable snapshots.",
 "pitfall": "Not taking snapshots — then a broken lab means reinstalling from scratch and you give up.",
},
"P1-07": {
 "overview": "Add 'eyes' to your lab: install Sysmon on your VMs and ship the logs to a free SIEM so you can SEE attacks as they happen. This turns every later exercise into a learning loop.",
 "steps": [
  "On each Windows VM, install Sysmon with the SwiftOnSecurity config.",
  "Stand up a free SIEM — Wazuh is the easiest all-in-one for beginners.",
  "Install the Wazuh agent on your VMs so their logs flow to the dashboard.",
  "Confirm it works: do something on a VM and watch the event show up in the SIEM.",
 ],
 "tools": ["Sysmon", "Wazuh (or Elastic)", "SwiftOnSecurity config"],
 "resources": R(("Wazuh — quickstart", "https://documentation.wazuh.com/current/quickstart.html"), ("Sysmon docs", "https://learn.microsoft.com/sysinternals/downloads/sysmon")),
 "doneWhen": "An action on a VM appears as a searchable event in your SIEM dashboard.",
 "pitfall": "Giving the SIEM VM too little RAM — it'll crawl and you'll stop using it. Give it 4GB+.",
},
"P1-08": {
 "overview": "GOAD (Game Of Active Directory) is a free, pre-built vulnerable AD lab. Deploy it and use BloodHound to draw the attack map — this becomes your playground for Phase 2.",
 "steps": [
  "Follow the GOAD install guide to deploy it (it automates building several vulnerable VMs).",
  "Install BloodHound Community Edition and its collector, SharpHound.",
  "Run SharpHound to collect data, then load it into BloodHound to see the graph of users, computers, and attack paths.",
  "Pick ONE path the graph shows and explain it out loud in plain English.",
 ],
 "tools": ["GOAD", "BloodHound Community Edition", "SharpHound"],
 "resources": R(("GOAD project", "https://github.com/Orange-Cyberdefense/GOAD"), ("BloodHound docs", "https://bloodhound.readthedocs.io")),
 "doneWhen": "BloodHound shows the GOAD graph and you can describe one attack edge in your own words.",
 "pitfall": "Deploying GOAD anywhere reachable from the internet — keep it fully isolated; it is deliberately vulnerable.",
},
"P1-09": {
 "overview": "Hands-on with tokens: compare the token of a normal program vs an admin one, and see how integrity levels differ. This makes the abstract 'token' idea concrete.",
 "steps": [
  "Open two programs — one normal, one 'as administrator'.",
  "In System Informer, open each process's Properties -> Token tab and compare integrity level and privileges.",
  "Note which privileges only the admin one has (e.g. SeDebugPrivilege).",
  "Write down: 'to go from medium to high integrity, an attacker needs ___' (that's privilege escalation, previewed).",
 ],
 "tools": ["System Informer / Process Hacker", "whoami /all", "A lab VM"],
 "resources": R(("HackTricks — Windows tokens", "https://book.hacktricks.xyz")),
 "doneWhen": "You can point at two processes and explain why one has more power than the other via its token.",
 "pitfall": "Doing this on your host machine instead of a VM — always practise in the lab.",
},
"P1-10": {
 "overview": "See a defense fire in real time: AMSI is Windows' in-memory script scanner. Trigger it with a standard test string and watch the alert appear in your SIEM — a satisfying attack->detection loop.",
 "steps": [
  "In PowerShell on a lab VM, use the standard AMSI test string (a designated, non-malicious trigger).",
  "Watch it get blocked — that's AMSI working.",
  "Go to your SIEM / Event Viewer and find the event that recorded it.",
  "Reflect: later phases are largely about NOT triggering this — but first, see it trigger.",
 ],
 "tools": ["PowerShell", "Your SIEM / Event Viewer", "A lab VM"],
 "resources": R(("Microsoft — AMSI", "https://learn.microsoft.com/windows/win32/amsi/antimalware-scan-interface-portal")),
 "doneWhen": "You triggered AMSI on purpose and found the matching log entry.",
 "pitfall": "Using real malware to 'test' — never needed. A designated test string is enough and safe.",
},
"P1-11": {
 "overview": "Write your first real offensive-style tool: a tiny C# program that lists running processes by calling Windows directly (P/Invoke), instead of the easy built-in class.",
 "steps": [
  "Start from a working C# console app.",
  "Find the P/Invoke signature for a process-listing API on pinvoke.net (e.g. toolhelp snapshots).",
  "Wire it up so your program prints process names and IDs.",
  "Compare: it does the same as Task Manager, but YOU called the Windows API to do it.",
 ],
 "tools": ["Visual Studio", "pinvoke.net", "C#"],
 "resources": R(("pinvoke.net — CreateToolhelp32Snapshot", "https://www.pinvoke.net"), ("ired.team — offensive C#", "https://www.ired.team")),
 "doneWhen": "Your own C# tool lists processes using a P/Invoke call (not System.Diagnostics).",
 "pitfall": "Copying a whole tool without understanding the P/Invoke line — the point is to understand the API call.",
},
"P1-12": {
 "overview": "A checkpoint, no notes. Kerberos is the heart of AD attacks — prove you can explain how it hands out tickets and where the famous attacks plug in.",
 "steps": [
  "Draw the Kerberos flow from memory: client -> gets a TGT -> uses it to get a TGS -> presents it to a service.",
  "For each step, name one attack that abuses it (AS-REP roast, Kerberoast, ticket forgery) — just name and place them.",
  "Explain it out loud to someone (or record yourself) with no notes.",
 ],
 "tools": ["Whiteboard / paper", "Your own study notes (used before the test, not during)"],
 "resources": R(("HackTricks — Kerberos", "https://book.hacktricks.xyz")),
 "doneWhen": "You can whiteboard the TGT/TGS exchange and place two attacks on it — from memory.",
 "pitfall": "Memorising attack names without knowing WHERE in the flow they happen.",
},
"P1-13": {
 "overview": "The Phase 1 hands-on checkpoint: prove your lab works end to end by reading your own SIEM events AND compiling your own P/Invoke tool. If both work, you're ready for Phase 2.",
 "steps": [
  "Do a small action on a VM and successfully find its event in your SIEM — no help.",
  "Compile and run your P/Invoke process-lister from P1-11.",
  "If either fails, fix it now — Phase 2 assumes a working lab and toolchain.",
 ],
 "tools": ["Your SIEM", "Visual Studio", "Your lab VMs"],
 "resources": R(("(revisit) Wazuh docs", "https://documentation.wazuh.com")),
 "doneWhen": "You independently found a SIEM event AND ran your own compiled tool in the same sitting.",
 "pitfall": "Rushing past a half-working lab — every later phase compounds on this foundation.",
},
})
# ============================== BEGINNER · PHASE 2 ==============================
BEGINNER.update({
"P2-01": {
 "overview": "Recon inside Active Directory: before attacking, learn to map who can do what. BloodHound turns a messy directory into a picture of attack paths.",
 "steps": [
  "In your GOAD lab, run SharpHound as a normal domain user to collect data.",
  "Load it into BloodHound and explore: users, groups, sessions, and the 'Shortest Path to Domain Admins' query.",
  "Learn the basic LDAP queries that find service accounts and admins.",
  "Goal: from a low-priv foothold, describe (not yet execute) a path toward Domain Admin.",
 ],
 "tools": ["SharpHound", "BloodHound CE", "PowerView (read source)"],
 "resources": R(("BloodHound docs", "https://bloodhound.readthedocs.io"), ("HackTricks — AD enumeration", "https://book.hacktricks.xyz")),
 "doneWhen": "You collected data with SharpHound and used BloodHound to find a path to Domain Admin in your lab.",
 "pitfall": "Running noisy tools without watching your SIEM — recon leaves traces too; notice them.",
},
"P2-02": {
 "overview": "Credential access: the family of techniques that steal or crack passwords and hashes in AD. These are the 'bread and butter' AD attacks.",
 "steps": [
  "Learn each by name and what it targets: Kerberoast (service account hashes), AS-REP roast (users without pre-auth), DCSync (pull hashes from the DC), LSASS/SAM dumping.",
  "Try Kerberoasting in GOAD with Rubeus or impacket, then crack the hash offline with hashcat.",
  "Watch your SIEM: note the event a Kerberoast request generates (4769).",
  "Keep a table: attack -> what it steals -> the log it makes.",
 ],
 "tools": ["Rubeus", "impacket (GetUserSPNs, secretsdump)", "hashcat"],
 "resources": R(("HackTricks — Kerberoasting", "https://book.hacktricks.xyz"), ("Certipy/impacket docs", "https://github.com/fortra/impacket")),
 "doneWhen": "You Kerberoasted a service account in the lab and cracked its password offline.",
 "pitfall": "Cracking hashes from anything but your own lab — only ever crack credentials you're authorized to test.",
},
"P2-03": {
 "overview": "Privilege escalation in AD by abusing permissions (ACLs) and delegation. Often the path to Domain Admin isn't an exploit — it's a misconfigured permission.",
 "steps": [
  "Learn the dangerous rights: GenericAll, WriteDACL, and what delegation (constrained/unconstrained/RBCD) means.",
  "In BloodHound, find an edge like 'User X has GenericAll over Group Y' and follow the abuse instructions BloodHound gives.",
  "Execute one ACL-abuse path in GOAD end to end.",
  "Explain WHY the permission was dangerous, not just the command.",
 ],
 "tools": ["BloodHound", "PowerView", "Rubeus (for delegation)"],
 "resources": R(("HackTricks — abusing AD ACLs/ACEs", "https://book.hacktricks.xyz"), ("BloodHound — edge help", "https://bloodhound.readthedocs.io")),
 "doneWhen": "You escalated privileges in the lab by abusing one ACL or delegation misconfiguration.",
 "pitfall": "Running the command without understanding the permission — you won't spot the same flaw in a real assessment.",
},
"P2-04": {
 "overview": "AD Certificate Services (ADCS) attacks — the 'ESC' family. Misconfigured certificate templates can hand you Domain Admin. Powerful and very common in real networks.",
 "steps": [
  "Understand the idea: certificates can prove identity; a bad template lets you request a cert AS someone else.",
  "Read the ESC1-ESC8 summaries (start with ESC1 and ESC8 — the most common).",
  "In a lab with ADCS, use Certipy to find (`find`) vulnerable templates.",
  "Don't try to memorise all 14 at once — understand ESC1 deeply first.",
 ],
 "tools": ["Certipy", "A lab with ADCS installed"],
 "resources": R(("SpecterOps — Certified Pre-Owned", "https://posts.specterops.io/certified-pre-owned-d95910965cd2"), ("Certipy", "https://github.com/ly4k/Certipy")),
 "doneWhen": "You can explain ESC1 in plain words and Certipy lists a vulnerable template in your lab.",
 "pitfall": "Drowning trying to learn ESC1-ESC14 at once — depth on one beats shallow on all.",
},
"P2-05": {
 "overview": "Lateral movement: once you have one machine or one credential, how you hop to the next. Pass-the-Hash, Pass-the-Ticket, and remote-execution methods.",
 "steps": [
  "Learn the concepts: PtH (use a hash instead of a password), PtT (use a Kerberos ticket), and exec methods (WMI, WinRM, PsExec, SMB).",
  "In the lab, take a hash you dumped and use it to authenticate to another machine (impacket's tools).",
  "Try two different execution methods and compare the logs each leaves.",
  "Note which method is 'quieter' in your SIEM.",
 ],
 "tools": ["impacket (psexec, wmiexec, smbexec)", "Rubeus / Mimikatz (lab)", "evil-winrm"],
 "resources": R(("HackTricks — lateral movement", "https://book.hacktricks.xyz")),
 "doneWhen": "You moved from one lab machine to another using a stolen hash or ticket.",
 "pitfall": "Only ever using PsExec — it's the loudest. Learn several so you can pick by situation.",
},
"P2-06": {
 "overview": "Persistence: how attackers keep access after the first compromise. Golden/Silver tickets and other AD backdoors. Understanding these also teaches you how to detect them.",
 "steps": [
  "Learn what a Golden Ticket is (forged TGT using the krbtgt hash) vs a Silver Ticket (forged service ticket).",
  "In the lab, after getting the krbtgt hash, forge a Golden Ticket and use it.",
  "Immediately look at how you'd DETECT it (unusual ticket lifetimes, anomalies).",
  "Understand this is 'game over' persistence — and why rotating krbtgt twice is the fix.",
 ],
 "tools": ["Mimikatz / Rubeus (lab)", "impacket ticketer"],
 "resources": R(("HackTricks — Golden/Silver tickets", "https://book.hacktricks.xyz")),
 "doneWhen": "You forged and used a Golden Ticket in the lab and can describe how a defender would catch it.",
 "pitfall": "Forgetting persistence is the most heavily-monitored area — study the detection alongside the attack.",
},
"P2-07": {
 "overview": "Trusts: how separate domains/forests relate, and how attackers cross between them. This is how a foothold in one place becomes control of another.",
 "steps": [
  "Learn what a trust is and the two directions (one-way vs two-way, intra- vs inter-forest).",
  "Understand SID history and how it can carry privileges across a trust.",
  "In a multi-domain lab (GOAD has this), map the trusts in BloodHound.",
  "Describe a path that starts in one domain and ends with control of another.",
 ],
 "tools": ["BloodHound", "Rubeus", "impacket"],
 "resources": R(("HackTricks — domain/forest trusts", "https://book.hacktricks.xyz")),
 "doneWhen": "You mapped the trusts in your lab and described a cross-domain attack path.",
 "pitfall": "Assuming a forest boundary is a hard security boundary — it often isn't, and that's the point.",
},
"P2-08": {
 "overview": "Your first full 'purple' exercise: run a complete attack chain in GOAD WHILE your SIEM records, then write the detections. This is where attacker and defender skills fuse.",
 "steps": [
  "Plan a chain: foothold -> Kerberoast -> ACL abuse -> DCSync. Write it down first.",
  "Execute it step by step in GOAD with your SIEM running.",
  "For each step, find the events it produced and write a detection note (which event, what threshold).",
  "Produce a short 'attack + detection' writeup — this is a mini real-world deliverable.",
 ],
 "tools": ["GOAD", "Your SIEM (Wazuh/Elastic)", "Rubeus/impacket"],
 "resources": R(("MITRE ATT&CK", "https://attack.mitre.org"), ("Sigma rules", "https://github.com/SigmaHQ/sigma")),
 "doneWhen": "You executed a multi-step chain and wrote a detection for every step from your own SIEM data.",
 "pitfall": "Running the chain but never checking the logs — the detections are the real learning here.",
},
"P2-09": {
 "overview": "HTB Pro Lab 'Dante' — a guided, beginner-friendly multi-machine lab to warm up your methodology (not pure AD, broad fundamentals).",
 "steps": [
  "Get an HTB subscription and start the Dante Pro Lab.",
  "Work it methodically: enumerate -> foothold -> escalate -> pivot. Take notes as you go.",
  "When stuck, learn the concept behind the hint rather than just copying the answer.",
  "Keep a clean notes file — you're building a reusable methodology.",
 ],
 "tools": ["Hack The Box (Dante Pro Lab)", "A note-taking system", "Kali/ParrotOS"],
 "resources": R(("Hack The Box", "https://www.hackthebox.com")),
 "doneWhen": "You completed Dante and have written notes capturing your repeatable methodology.",
 "pitfall": "Rushing with walkthroughs — the value is building YOUR process, not finishing fast.",
},
"P2-10": {
 "overview": "HTB Pro Lab 'Zephyr' — an intermediate AD red-team simulation. A big step up from Dante; this is closer to a real engagement.",
 "steps": [
  "Start Zephyr after Dante. Expect it to be hard — that's the point.",
  "Apply everything from P2-01..P2-08: enumerate with BloodHound, roast, abuse ACLs, move laterally.",
  "Track your path so you could reproduce it and explain it to someone.",
  "Write a short after-action of the full compromise path.",
 ],
 "tools": ["Hack The Box (Zephyr Pro Lab)", "BloodHound", "impacket/Rubeus"],
 "resources": R(("Hack The Box", "https://www.hackthebox.com")),
 "doneWhen": "You reached the objective in Zephyr and can diagram the full path from memory.",
 "pitfall": "Skipping notes — in a real engagement, an undocumented path is a path you didn't really do.",
},
"P2-11": {
 "overview": "Execute one full ADCS attack path end to end with Certipy — turning the ESC theory from P2-04 into a real domain compromise in the lab.",
 "steps": [
  "Pick ESC1 or ESC8 (the most common).",
  "Use `certipy find` to confirm the vulnerable template in your lab.",
  "Follow the ESC1/ESC8 steps to request a certificate and use it to authenticate as a privileged account.",
  "Write down each command AND why it works.",
 ],
 "tools": ["Certipy", "impacket", "A lab with ADCS"],
 "resources": R(("Certipy wiki", "https://github.com/ly4k/Certipy/wiki"), ("Certified Pre-Owned", "https://posts.specterops.io/certified-pre-owned-d95910965cd2")),
 "doneWhen": "You went from a vulnerable template to privileged access via one full ESC path in the lab.",
 "pitfall": "Copy-pasting Certipy commands without understanding which ESC you're doing — know the mechanism.",
},
"P2-12": {
 "overview": "Cross a trust boundary: start in one domain and compromise another through trust abuse. Ties together P2-06 (tickets) and P2-07 (trusts).",
 "steps": [
  "In a multi-domain lab, confirm the trust direction with BloodHound.",
  "Compromise the first domain to the point of having the needed keys/hashes.",
  "Use SID history or a forged inter-realm ticket to reach the second domain.",
  "Diagram the whole cross-domain path.",
 ],
 "tools": ["Rubeus", "impacket", "BloodHound", "Mimikatz (lab)"],
 "resources": R(("HackTricks — cross-forest", "https://book.hacktricks.xyz")),
 "doneWhen": "You compromised a second domain across a trust in the lab and documented the path.",
 "pitfall": "Attempting this before you're solid on tickets — it builds directly on golden/silver ticket skills.",
},
"P2-13": {
 "overview": "Do a full lab compromise with NO Metasploit and NO Mimikatz 'easy button' — only Rubeus/Certipy/impacket. This forces real understanding over point-and-click.",
 "steps": [
  "Pick a lab you can already beat with the easy tools.",
  "Redo it using only the manual toolkit (impacket, Rubeus, Certipy, evil-winrm).",
  "When something's harder, that friction is teaching you what the easy button hid.",
  "Note what you learned that the automated path had hidden from you.",
 ],
 "tools": ["impacket", "Rubeus", "Certipy", "evil-winrm"],
 "resources": R(("impacket", "https://github.com/fortra/impacket"), ("Rubeus", "https://github.com/GhostPack/Rubeus")),
 "doneWhen": "You fully compromised a lab without Metasploit or Mimikatz's convenience features.",
 "pitfall": "Falling back to the easy button when stuck — pushing through is the entire exercise.",
},
"P2-14": {
 "overview": "The Phase 2 real test: own a FRESH, unseen AD lab entirely on your own, then produce a path diagram and remediation advice — exactly what a junior red teamer delivers.",
 "steps": [
  "Get an AD lab you haven't seen (a new HTB box/lab or a friend's build).",
  "Compromise it unassisted, taking screenshots and notes as evidence.",
  "Draw the attack path as a diagram.",
  "Write remediation: for each step, how the defender should have stopped it.",
 ],
 "tools": ["An unseen AD lab", "diagramming tool (draw.io)", "BloodHound"],
 "resources": R(("draw.io", "https://app.diagrams.net")),
 "doneWhen": "You independently owned a new AD lab and produced a path diagram plus remediation.",
 "pitfall": "Judging success only by 'got Domain Admin' — the diagram and remediation are half the job.",
},
"P2-15": {
 "overview": "Milestone: pass CRTP (Certified Red Team Professional) — the industry entry cert for practical AD attacks. A real, exam-based proof of your Phase 2 skills.",
 "steps": [
  "Enroll in Altered Security's CRTP course and work through all the labs.",
  "Practise the exam-style objectives until the core attacks are muscle memory.",
  "Book and pass the 24-hour practical exam, then write the report.",
  "This is optional-but-recommended; the skills matter more than the badge, but the badge helps.",
 ],
 "tools": ["Altered Security CRTP course + lab", "Your notes"],
 "resources": R(("Altered Security — CRTP", "https://www.alteredsecurity.com/gcb")),
 "doneWhen": "You passed the CRTP exam and submitted the report.",
 "pitfall": "Treating the cert as the goal — it's a checkpoint proving the skills you've been building, not the finish line.",
},
})
# ============================== BEGINNER · PHASE 3 ==============================
BEGINNER.update({
"P3-01": {
 "overview": "Learn how a Command-and-Control (C2) framework works — the 'remote control' an operator uses to task an implant. Concept-first; make sure Phases 1-2 are solid before diving in.",
 "steps": [
  "Learn the pieces: operator -> team server -> listener -> a beacon/agent that calls back on a sleep interval.",
  "Understand 'sleep' and 'jitter' (how often and how randomly the agent checks in) and why they affect detection.",
  "Spin up a free C2 (Sliver is beginner-friendly) in your lab and run a BENIGN agent between two of your own VMs.",
  "Watch the callbacks in your SIEM / Wireshark — see what 'normal' C2 traffic looks like.",
 ],
 "tools": ["Sliver (open-source C2)", "Your lab VMs", "Wireshark", "Your SIEM"],
 "resources": R(("Sliver wiki", "https://github.com/BishopFox/sliver/wiki"), ("The C2 Matrix", "https://www.thec2matrix.com")),
 "doneWhen": "You ran a benign agent in your lab and can draw the operator->team server->listener->beacon chain from memory.",
 "pitfall": "Jumping to evasion before you understand the tasking model — learn how C2 works first; hiding it comes in Phase 4.",
},
"P3-02": {
 "overview": "An introduction to how offensive payloads run code in memory. This is real malware-development territory — strictly lab-only, benign test payloads, on machines you own.",
 "steps": [
  "Learn the vocabulary: shellcode, a 'loader' that runs it, and 'injection' (running code inside another process).",
  "Read what the common techniques do by name: classic injection, APC, thread hijack, process hollowing.",
  "Follow a tutorial to run BENIGN shellcode (e.g. a calc/messagebox stub, or a Sliver agent) via a simple loader in your lab.",
  "Keep it in the lab and understand each line — don't run anything you can't explain.",
 ],
 "tools": ["Visual Studio (C#)", "msfvenom (benign stub) or Sliver shellcode", "A lab VM", "x64dbg (optional)"],
 "resources": R(("ired.team — process injection", "https://www.ired.team"), ("MalDev Academy", "https://maldevacademy.com")),
 "doneWhen": "You ran benign shellcode through a basic loader in your lab and can explain what injection means.",
 "pitfall": "Downloading random 'stealer' code to try — you only ever need benign test payloads to learn the mechanics.",
},
"P3-03": {
 "overview": "Understand the Windows API from an offensive angle, and why 'syscalls' exist as an evasion idea. Builds directly on your C/C# from Phase 1.",
 "steps": [
  "Learn how a normal program calls Windows: your code -> a Win32 API (kernel32) -> ntdll -> a syscall into the kernel.",
  "Understand why security products 'hook' those APIs to watch you, and how calling the syscall directly can skip the hook.",
  "Read one 'direct syscall' explainer — you don't need to write one yet, just grasp the concept.",
  "Note where each layer is and which one the EDR watches.",
 ],
 "tools": ["Visual Studio / C", "PE-bear (inspect ntdll)", "reference: ired.team"],
 "resources": R(("ired.team — syscalls", "https://www.ired.team"), ("Microsoft — Win32 API", "https://learn.microsoft.com/windows/win32/api/")),
 "doneWhen": "You can draw the call path (your code -> Win32 -> ntdll -> syscall) and say where an EDR typically hooks.",
 "pitfall": "Collecting syscall tools without understanding the call path — the concept matters more than any one PoC.",
},
"P3-04": {
 "overview": "Learn what 'redirector' infrastructure is: the servers that sit between your C2 and the target so your real server stays hidden. Intro level — concepts and a simple setup.",
 "steps": [
  "Understand the idea: target talks to a cheap throwaway 'redirector' which forwards to your hidden team server.",
  "Learn why operators use TLS, real domains, and categorization to blend in.",
  "In your lab (or a cheap VPS you own), set up a basic nginx reverse proxy forwarding to a C2 listener.",
  "Learn what 'infrastructure as code' (Terraform/Ansible) means — automating this setup — even if you script it by hand first.",
 ],
 "tools": ["nginx / Apache", "A VPS you own (or a lab VM)", "Terraform (intro)", "Let's Encrypt / certbot"],
 "resources": R(("Red Team Infrastructure Wiki", "https://github.com/bluscreenofjeff/Red-Team-Infrastructure-Wiki"), ("Terraform intro", "https://developer.hashicorp.com/terraform/intro")),
 "doneWhen": "You stood up a simple reverse proxy that forwards traffic to a C2 listener in your lab.",
 "pitfall": "Exposing a real C2 team server directly to the internet — the whole point of a redirector is that you never do that.",
},
"P3-05": {
 "overview": "Get hands-on with Cobalt Strike, the industry-standard commercial C2 — the tool many real engagements use. (Requires a licence; if you don't have one, do P3-06 with a free C2 instead.)",
 "steps": [
  "If you have access, set up a team server and connect the client in your lab.",
  "Learn the core workflow: listener -> generate a beacon -> interact -> run tasks -> pivot.",
  "Practise the built-in AD tooling and how beacon 'sleep' affects your interactivity.",
  "Do everything against your own lab hosts only.",
 ],
 "tools": ["Cobalt Strike (licensed)", "Your lab VMs"],
 "resources": R(("Cobalt Strike documentation", "https://hstechdocs.helpsystems.com/manuals/cobaltstrike/current/userguide/content/topics/welcome_main.htm")),
 "doneWhen": "You ran a full listener->beacon->task->pivot workflow against your lab.",
 "pitfall": "No licence? Don't pirate it — the free C2s in P3-06 teach the same concepts perfectly well.",
},
"P3-06": {
 "overview": "Master an open-source C2 (Sliver, Mythic, or Havoc) — free, powerful, and great for learning the same tradecraft as commercial tools.",
 "steps": [
  "Pick one (Sliver is the easiest first) and install its team server in your lab.",
  "Generate a benign agent, run it on a lab VM, and complete the task/pivot workflow.",
  "Compare it to what you learned about Cobalt Strike — the concepts transfer.",
  "Explore its profiles/config to see how you'd shape its traffic later.",
 ],
 "tools": ["Sliver / Mythic / Havoc", "Your lab VMs", "Docker (for Mythic)"],
 "resources": R(("Sliver wiki", "https://github.com/BishopFox/sliver/wiki"), ("Mythic docs", "https://docs.mythic-c2.net")),
 "doneWhen": "You ran an end-to-end op (deploy agent -> task -> pivot) with an open-source C2 in your lab.",
 "pitfall": "Flitting between three C2s shallowly — get genuinely fluent in one before sampling the others.",
},
"P3-07": {
 "overview": "Write your own simple shellcode loader — once in C# and once in C — that runs a BENIGN beacon in your lab. Your first real offensive tool.",
 "steps": [
  "Generate a benign agent's shellcode (e.g. a Sliver agent for your lab).",
  "Write a minimal C# loader: allocate memory, copy the shellcode, run it. Test in the lab.",
  "Do the same in C to feel the raw Win32 calls (VirtualAlloc, CreateThread).",
  "Explain every API call you used and why.",
 ],
 "tools": ["Visual Studio (C# and C)", "Sliver (benign shellcode)", "A lab VM"],
 "resources": R(("ired.team — shellcode execution", "https://www.ired.team"), ("MalDev Academy", "https://maldevacademy.com")),
 "doneWhen": "Both your C# and C loaders run a benign beacon in the lab and you understand each API call.",
 "pitfall": "Copying a loader wholesale — write it yourself so you understand allocation, copy, and execute.",
},
"P3-08": {
 "overview": "Stand up HTTP + DNS redirector infrastructure with Terraform and run a lab op through it. Turns the P3-04 concepts into automated, reproducible infra.",
 "steps": [
  "Write a small Terraform config that provisions a VPS you own and installs an nginx (HTTP) redirector.",
  "Add a DNS redirector concept (a domain you own pointing at the redirector).",
  "Run a benign agent through the redirector to your hidden team server.",
  "Tear it down with Terraform — reproducibility is the point.",
 ],
 "tools": ["Terraform", "A cloud account you own", "nginx", "A domain you own"],
 "resources": R(("Red Team Infrastructure Wiki", "https://github.com/bluscreenofjeff/Red-Team-Infrastructure-Wiki"), ("Terraform docs", "https://developer.hashicorp.com/terraform/docs")),
 "doneWhen": "An agent reaches your team server only via the Terraform-provisioned redirector, and you can rebuild it from code.",
 "pitfall": "Hardcoding secrets/keys into Terraform files you might commit — keep them out of version control.",
},
"P3-09": {
 "overview": "Author a C2 'malleable' profile (traffic-shaping config) and watch how it changes your network signature in the SIEM. Where offense meets detection-awareness.",
 "steps": [
  "Read a sample malleable/HTTP profile and understand which parts shape the request/response.",
  "Change a few fields (user-agent, URIs, headers) and re-run a benign beacon in your lab.",
  "Capture before/after in your SIEM / Wireshark and note what changed.",
  "Write down which signals a defender could still key on.",
 ],
 "tools": ["Your C2's profile system", "Wireshark", "Your SIEM"],
 "resources": R(("Cobalt Strike Malleable C2 reference", "https://hstechdocs.helpsystems.com/manuals/cobaltstrike/current/userguide/content/topics/malleable-c2_main.htm")),
 "doneWhen": "You changed a profile and can show the before/after difference in captured traffic.",
 "pitfall": "Assuming a custom profile makes you invisible — you're changing the signature, not removing it.",
},
"P3-10": {
 "overview": "Implement three injection techniques and compare the Sysmon/ETW footprint of each. Directly connects your loaders (P3-07) to detection.",
 "steps": [
  "Pick three techniques (e.g. classic CreateRemoteThread, APC, and process hollowing).",
  "Run each with a benign payload in your lab, one at a time.",
  "For each, collect the Sysmon events (e.g. CreateRemoteThread=8) and note what fired.",
  "Rank them from noisiest to quietest and explain why.",
 ],
 "tools": ["Your loaders", "Sysmon", "Your SIEM", "A lab VM"],
 "resources": R(("ired.team — process injection", "https://www.ired.team"), ("Sysmon docs", "https://learn.microsoft.com/sysinternals/downloads/sysmon")),
 "doneWhen": "You have a side-by-side note of what telemetry each of three injection techniques produced.",
 "pitfall": "Only trying the loudest technique — the learning is in comparing footprints.",
},
"P3-11": {
 "overview": "Work through the Sektor7 'RED TEAM Operator: Malware Development Essentials' course — a structured, beginner-friendly path into offensive tooling.",
 "steps": [
  "Enroll and follow the modules in order; code along, don't just watch.",
  "Rebuild each example yourself in your lab.",
  "Keep a personal cheat-sheet of the techniques as you go.",
  "Everything runs in your lab against your own machines.",
 ],
 "tools": ["Sektor7 course", "Visual Studio", "A lab VM"],
 "resources": R(("Sektor7 Institute", "https://institute.sektor7.net")),
 "doneWhen": "You completed the course and rebuilt its core examples from scratch in your lab.",
 "pitfall": "Watching passively — type and run every example, or none of it will stick.",
},
})
BEGINNER.update({
"P3-12": {
 "overview": "Work through MalDev Academy's core modules (loaders, injection, evasion) — a modern, structured malware-development curriculum, all in your own lab.",
 "steps": [
  "Follow the loader and injection modules in order, coding each one yourself.",
  "Run every example against your own lab VMs with benign payloads.",
  "Note how each technique maps to the telemetry you learned about in Phase 1.",
  "Build a small personal library of the primitives you've learned.",
 ],
 "tools": ["MalDev Academy", "Visual Studio", "A lab VM"],
 "resources": R(("MalDev Academy", "https://maldevacademy.com")),
 "doneWhen": "You completed the core modules and can rebuild a loader + one injection technique from memory.",
 "pitfall": "Hoarding course code you never compile — the reps in the lab are what build the skill.",
},
"P3-13": {
 "overview": "The Phase 3 test: a loader YOU wrote gets a benign beacon past default-config Windows Defender in your lab, and you can explain why each evasion step works.",
 "steps": [
  "Start from your own loader (P3-07). Test it against a lab VM with default Defender on.",
  "Add evasion iteratively (e.g. avoid known-bad API patterns), testing after each change.",
  "For every change, write one sentence on WHY it helps.",
  "Keep the payload benign — this is about the loader, not the payload.",
 ],
 "tools": ["Your loader", "A Defender-enabled lab VM", "Benign shellcode"],
 "resources": R(("MalDev Academy", "https://maldevacademy.com"), ("ired.team — evasion", "https://www.ired.team")),
 "doneWhen": "Your own loader runs a benign beacon on a default-Defender lab VM and you can justify each evasion.",
 "pitfall": "Chasing 'FUD' crypters you didn't write — you won't learn, and they break the moment signatures update.",
},
"P3-14": {
 "overview": "Milestone: pass CRTO (Certified Red Team Operator, Zero-Point Security) — the go-to practical cert for C2 tradecraft and evasion. Optional but highly regarded.",
 "steps": [
  "Take the CRTO course and complete its Cobalt Strike lab exercises.",
  "Practise the full attack chain until it's second nature.",
  "Book and pass the practical exam, then write the report.",
  "Remember: the exam proves the tradecraft you've built across Phase 3.",
 ],
 "tools": ["Zero-Point Security CRTO course + lab"],
 "resources": R(("Zero-Point Security — CRTO", "https://training.zeropointsecurity.co.uk/courses/red-team-ops")),
 "doneWhen": "You passed CRTO and submitted the report.",
 "pitfall": "Cramming exam steps without the underlying tradecraft — CRTO rewards understanding, not memorised commands.",
},
})
BEGINNER.update({
"P4-01": {
 "overview": "Learn what AMSI is and, conceptually, how it gets bypassed — and importantly, the detection for each bypass. Defender-awareness, in the lab, on your own machines.",
 "steps": [
  "Recall AMSI from Phase 1: it scans scripts/memory for bad content before they run.",
  "Read (conceptually) how bypasses work — patching the check, or provider tricks.",
  "In your lab, observe a known bypass being used and, crucially, find the log/behaviour that detects it.",
  "Write a mini table: bypass idea -> how a defender catches it.",
 ],
 "tools": ["PowerShell", "Your SIEM", "A lab VM"],
 "resources": R(("Microsoft — AMSI", "https://learn.microsoft.com/windows/win32/amsi/antimalware-scan-interface-portal"), ("ired.team — AMSI", "https://www.ired.team")),
 "doneWhen": "You can explain one AMSI bypass idea AND the detection that would catch it.",
 "pitfall": "Learning bypasses without their detections — the modern operator reasons about both sides.",
},
"P4-02": {
 "overview": "Understand ETW (Event Tracing for Windows) and, at a concept level, 'blinding' it — plus why that's increasingly detected. Awareness first, lab-only.",
 "steps": [
  "Learn what ETW is: a rich telemetry pipeline security tools consume.",
  "Understand conceptually why attackers try to tamper with it and the trade-offs (it's noisy/detected now).",
  "In the lab, look at what an ETW provider emits for a technique you already know.",
  "Note why tampering itself creates a signal.",
 ],
 "tools": ["PerfView / logman", "Your SIEM", "A lab VM"],
 "resources": R(("ired.team — ETW", "https://www.ired.team"), ("Microsoft — ETW", "https://learn.microsoft.com/windows/win32/etw/about-event-tracing")),
 "doneWhen": "You can explain what ETW gives defenders and why blinding it is itself detectable.",
 "pitfall": "Assuming ETW tampering is 'stealth' — it's one of the most-watched behaviours today.",
},
"P4-03": {
 "overview": "The advanced evasion concepts: unhooking, direct/indirect syscalls, call-stack spoofing, sleep-mask. This is deep tradecraft — grasp the ideas before any code.",
 "steps": [
  "Learn what 'hooking' means (an EDR patches ntdll to watch you) and 'unhooking' (restoring the clean copy).",
  "Revisit syscalls (P3-03) and why 'indirect' syscalls are stealthier than 'direct'.",
  "Understand sleep-mask/heap encryption at a high level: hiding your implant in memory while it sleeps.",
  "Don't implement yet — build the mental model first.",
 ],
 "tools": ["reference reading", "x64dbg (to see hooks)", "A lab VM"],
 "resources": R(("ired.team — evasion", "https://www.ired.team"), ("MalDev Academy", "https://maldevacademy.com")),
 "doneWhen": "You can explain hooking/unhooking and why indirect syscalls exist, in plain words.",
 "pitfall": "Copy-pasting an evasion framework you can't explain — you'll have no idea why it works or fails.",
},
"P4-04": {
 "overview": "Understand PPL, LSASS protection, and Credential Guard — the defenses that make credential theft hard, and what they mean for an operator.",
 "steps": [
  "Recall LSASS from Phase 1 (where credentials live) and why it's a target.",
  "Learn what PPL (Protected Process Light) and Credential Guard do to protect it.",
  "In a lab, turn these protections on and observe how credential-dumping behaves differently.",
  "Note what an attacker would need to work around them (and that you shouldn't expect an easy button).",
 ],
 "tools": ["A lab VM (Win 10/11)", "Group Policy", "your SIEM"],
 "resources": R(("Microsoft — Credential Guard", "https://learn.microsoft.com/windows/security/identity-protection/credential-guard/"), ("HackTricks — LSASS", "https://book.hacktricks.xyz")),
 "doneWhen": "You can explain what PPL and Credential Guard protect and why they raise the bar for credential theft.",
 "pitfall": "Assuming classic LSASS dumping always works — modern defenses often stop it cold.",
},
})
BEGINNER.update({
"P4-05": {
 "overview": "Learn what an EDR (Endpoint Detection & Response) actually sees — kernel callbacks, minifilters, ETW-TI. Knowing the sensor is the foundation of all evasion and detection.",
 "steps": [
  "Learn the sources an EDR taps: kernel callbacks (process/thread/image), file/registry minifilters, ETW-TI.",
  "Understand that an EDR builds a behavioural story, not just single events.",
  "In a lab with a free EDR, do a benign action and see what it records.",
  "Map: 'thing I did' -> 'what the EDR saw'.",
 ],
 "tools": ["Elastic Defend (free) or MDE trial", "A lab VM"],
 "resources": R(("Elastic Security docs", "https://www.elastic.co/guide/en/security/current/index.html"), ("MITRE ATT&CK — Data Sources", "https://attack.mitre.org/datasources/")),
 "doneWhen": "You can name three telemetry sources an EDR uses and show one event it captured from your action.",
 "pitfall": "Thinking of an EDR as 'antivirus' — it correlates behaviour over time, which is much harder to evade.",
},
"P4-06": {
 "overview": "Detection engineering basics: write Sigma rules, map to MITRE ATT&CK, and build detections in Elastic/Splunk. The blue-team skill every strong red teamer needs.",
 "steps": [
  "Learn the Sigma rule format (a portable detection YAML).",
  "Take a technique you performed and write a Sigma rule that would catch it.",
  "Convert/load it into your SIEM and test it against your own attack.",
  "Tag it with the ATT&CK technique ID.",
 ],
 "tools": ["Sigma", "Your SIEM (Elastic/Splunk)", "MITRE ATT&CK Navigator"],
 "resources": R(("Sigma (SigmaHQ)", "https://github.com/SigmaHQ/sigma"), ("MITRE ATT&CK", "https://attack.mitre.org")),
 "doneWhen": "You wrote a Sigma rule that fires on one of your own lab attacks.",
 "pitfall": "Writing rules you never test — an untested detection is just a guess.",
},
"P4-07": {
 "overview": "Deploy a real EDR in your lab and iterate your loaders against it. The big step from 'beat Defender' to 'understand a modern sensor'.",
 "steps": [
  "Stand up a free/eval EDR (Elastic Defend or MDE eval) on a lab VM.",
  "Run your benign loader and watch what the EDR flags.",
  "Change one thing, re-run, and observe the difference — a tight feedback loop.",
  "Keep notes on what triggered and what didn't.",
 ],
 "tools": ["Elastic Defend / MDE eval", "Your loaders", "A lab VM"],
 "resources": R(("Elastic Defend", "https://www.elastic.co/guide/en/security/current/install-endpoint.html")),
 "doneWhen": "You ran your loader against a real EDR and logged what it detected across a few iterations.",
 "pitfall": "Testing against Defender only and assuming EDRs behave the same — they see far more.",
},
"P4-08": {
 "overview": "Use a pre-built purple-team lab (DetectionLab / SimuLand / Splunk Attack Range) to run paired attack + detect exercises without building everything yourself.",
 "steps": [
  "Pick one project and follow its deploy guide (they automate a lot).",
  "Run a built-in attack scenario and watch the detections light up.",
  "Tweak the attack and see how the detection responds.",
  "Note what these give you that your hand-built lab doesn't.",
 ],
 "tools": ["DetectionLab / SimuLand / Splunk Attack Range"],
 "resources": R(("DetectionLab", "https://github.com/clong/DetectionLab"), ("Splunk Attack Range", "https://github.com/splunk/attack_range")),
 "doneWhen": "You ran one attack+detect scenario end to end in a pre-built purple lab.",
 "pitfall": "Getting stuck in setup — these can be heavy; use a project that matches your hardware.",
},
"P4-09": {
 "overview": "Use MITRE Caldera + Atomic Red Team to run a technique, observe the telemetry, and tune the detection. Automated adversary emulation for beginners.",
 "steps": [
  "Install Atomic Red Team and run a single atomic test for a technique you know.",
  "Watch the telemetry it produces in your SIEM/EDR.",
  "Tune or write a detection so it reliably catches that atomic.",
  "Try Caldera to chain a few techniques automatically.",
 ],
 "tools": ["Atomic Red Team", "MITRE Caldera", "Your SIEM"],
 "resources": R(("Atomic Red Team", "https://github.com/redcanaryco/atomic-red-team"), ("MITRE Caldera", "https://github.com/mitre/caldera")),
 "doneWhen": "You ran an atomic test, saw its telemetry, and tuned a detection that catches it.",
 "pitfall": "Running atomics blind on a machine you care about — use the lab; some tests make real changes.",
},
})
BEGINNER.update({
"P4-10": {
 "overview": "The evade -> re-detect loop, five times: evade Defender, then write the detection that re-catches you. The single best exercise for becoming detection-aware.",
 "steps": [
  "Get a benign technique past Defender in your lab.",
  "Then switch hats: write the Sigma/EDR rule that would catch what you just did.",
  "Verify your rule fires, then find a new evasion — and repeat five times.",
  "Keep a log of each round: evasion used -> detection written.",
 ],
 "tools": ["Your loaders", "Sigma", "Your SIEM/EDR", "A lab VM"],
 "resources": R(("Sigma", "https://github.com/SigmaHQ/sigma"), ("ired.team", "https://www.ired.team")),
 "doneWhen": "You completed five evade->re-detect rounds, each with a working detection.",
 "pitfall": "Only doing the evade half — the discipline of re-detecting is what makes this valuable.",
},
"P4-11": {
 "overview": "Build a 'telemetry budget' document: list every signal a full attack chain emits, and its mitigation. Trains you to think in signals, like a real operator.",
 "steps": [
  "Take an attack chain you can run in the lab.",
  "For each step, list every log/telemetry it produces (from your Phase-1 notes and SIEM).",
  "For each signal, note how you'd reduce or avoid it (or accept it).",
  "The result is a one-page 'what this op costs me in noise' doc.",
 ],
 "tools": ["Your SIEM", "A notes/spreadsheet tool"],
 "resources": R(("MITRE ATT&CK", "https://attack.mitre.org")),
 "doneWhen": "You produced a per-step telemetry budget for one full chain with mitigations.",
 "pitfall": "Listing only the obvious logs — the subtle signals are the ones that catch experienced operators.",
},
"P4-12": {
 "overview": "The Phase 4 test: a custom implant survives a REAL EDR through a multi-step chain, and you hand over a detection pack. Both sides of the coin.",
 "steps": [
  "Use your own tooling to run a benign multi-step chain against a real EDR in the lab.",
  "Where it's caught, iterate; where it survives, note why.",
  "Then write a detection pack (Sigma/EDR rules) that WOULD catch your chain.",
  "Deliver both: the red narrative and the blue detections.",
 ],
 "tools": ["Your implant/loaders", "A real EDR (lab)", "Sigma"],
 "resources": R(("Elastic Security", "https://www.elastic.co/security"), ("Sigma", "https://github.com/SigmaHQ/sigma")),
 "doneWhen": "Your chain survived a real EDR AND you produced detections that catch it.",
 "pitfall": "Declaring victory at 'it ran' — without the detection pack you've only done half the exercise.",
},
"P4-13": {
 "overview": "Milestone (optional): pass OffSec OSEP (PEN-300) — a well-known cert covering evasion and lateral movement. A solid external checkpoint for Phase 4 skills.",
 "steps": [
  "Take the PEN-300 course and work all the lab exercises.",
  "Focus on the evasion and AV/EDR-bypass material.",
  "Book and pass the 48-hour practical exam.",
  "Optional — skip if you're prioritising red-team-specific certs (CRTO/CRTL).",
 ],
 "tools": ["OffSec PEN-300 course + labs"],
 "resources": R(("OffSec — PEN-300 / OSEP", "https://www.offsec.com/courses/pen-300/")),
 "doneWhen": "You passed the OSEP exam.",
 "pitfall": "Chasing every cert — pick the ones that match your target role instead of collecting them all.",
},
})
BEGINNER.update({
"P5-01": {
 "overview": "Learn Entra ID (formerly Azure AD) — cloud identity: OAuth/OIDC, tokens (especially the PRT), conditional access, app registrations, and consent phishing. The cloud half of modern attacks.",
 "steps": [
  "Get a free Microsoft 365 developer tenant to practise in (yours to break).",
  "Learn the vocabulary: tenant, user, app registration, service principal, OAuth token, PRT, conditional access.",
  "Understand 'consent phishing' and the device-code flow at a concept level.",
  "Enumerate your own dev tenant with a read-only tool to see the objects.",
 ],
 "tools": ["Microsoft 365 developer tenant", "Microsoft Graph", "AADInternals (read-only, lab)"],
 "resources": R(("Microsoft — Entra ID", "https://learn.microsoft.com/entra/identity/"), ("AADInternals", "https://aadinternals.com")),
 "doneWhen": "You can explain what a PRT and conditional access are, using your own dev tenant to point at objects.",
 "pitfall": "Testing on a real company tenant — always use your own free developer tenant.",
},
"P5-02": {
 "overview": "Understand hybrid identity: how on-prem AD syncs to Entra via Entra Connect, and the attack paths in PHS/PTA/federation. Where on-prem and cloud meet.",
 "steps": [
  "Learn the three sync models: Password Hash Sync, Pass-Through Auth, and Federation.",
  "Understand why Entra Connect is a high-value target (it bridges both worlds).",
  "In a lab, set up (or read a walkthrough of) Entra Connect and see what syncs.",
  "Note, conceptually, the attack path each sync model exposes.",
 ],
 "tools": ["A lab tenant + lab AD", "Entra Connect", "reference reading"],
 "resources": R(("Microsoft — Entra Connect", "https://learn.microsoft.com/entra/identity/hybrid/connect/whatis-azure-ad-connect"), ("AADInternals", "https://aadinternals.com")),
 "doneWhen": "You can explain PHS vs PTA vs federation and why Entra Connect is a prime target.",
 "pitfall": "Blurring the sync models together — each has a distinct attack path, so keep them straight.",
},
"P5-03": {
 "overview": "Learn on-prem <-> cloud pivots: ADFS/PRT abuse, Intune, synced credentials, seamless SSO. How a foothold in one world becomes control of the other.",
 "steps": [
  "Understand the PRT as a 'cloud SSO token' and why stealing it is powerful.",
  "Learn how Intune (cloud device management) can push actions to endpoints.",
  "In a hybrid lab, trace how a synced credential could be used in the cloud.",
  "Sketch a pivot path in each direction (on-prem->cloud and cloud->on-prem).",
 ],
 "tools": ["Hybrid lab", "AADInternals (lab)", "reference reading"],
 "resources": R(("Microsoft — PRT", "https://learn.microsoft.com/entra/identity/devices/concept-primary-refresh-token"), ("dirkjanm blog — cloud attacks", "https://dirkjanm.io")),
 "doneWhen": "You can describe one on-prem->cloud and one cloud->on-prem pivot at a conceptual level.",
 "pitfall": "Thinking the network boundary contains an attacker — synced identity crosses it in both directions.",
},
"P5-04": {
 "overview": "Learn AWS attack basics: IAM privilege-escalation paths, role assumption, the instance metadata service (SSRF-to-creds), and the Pacu methodology. Cloud provider #1.",
 "steps": [
  "Learn IAM fundamentals: users, roles, policies, and what 'assume role' means.",
  "Understand the metadata service (169.254.169.254) and why SSRF can steal credentials from it.",
  "Set up a personal AWS account (free tier) and enumerate your own IAM with least privilege.",
  "Read the Pacu framework's methodology (don't run it against anything but your own account).",
 ],
 "tools": ["A personal AWS account (free tier)", "AWS CLI", "Pacu (own account only)"],
 "resources": R(("AWS IAM docs", "https://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html"), ("Pacu", "https://github.com/RhinoSecurityLabs/pacu")),
 "doneWhen": "You can explain one IAM priv-esc path and how metadata-service SSRF yields credentials.",
 "pitfall": "Running cloud attack tools against accounts you don't own — only ever your own AWS account.",
},
"P5-05": {
 "overview": "Learn GCP IAM and service accounts, plus containers/Kubernetes as a pivot surface (RBAC, SA tokens, escapes). Cloud provider #2 and the container angle.",
 "steps": [
  "Learn GCP IAM and what a service account (SA) is, and how SA tokens work.",
  "Understand Kubernetes basics: pods, RBAC, and the service-account token mounted in a pod.",
  "In a personal GCP project (free tier) or local Kubernetes (kind/minikube), poke at RBAC.",
  "Learn what a 'container escape' means conceptually.",
 ],
 "tools": ["Personal GCP project (free tier)", "kind/minikube (local k8s)", "kubectl"],
 "resources": R(("GCP IAM docs", "https://cloud.google.com/iam/docs"), ("Kubernetes RBAC", "https://kubernetes.io/docs/reference/access-authn-authz/rbac/")),
 "doneWhen": "You can explain SA tokens and how a pod's mounted token could be abused as a pivot.",
 "pitfall": "Skipping Kubernetes because it seems unrelated — containers are a huge modern pivot surface.",
},
})
BEGINNER.update({
"P5-06": {
 "overview": "Run a CloudGoat (AWS) scenario end to end and write up the attack path. A deliberately-vulnerable, safe playground for AWS attacks.",
 "steps": [
  "Deploy CloudGoat into your own AWS account (it uses Terraform).",
  "Pick a scenario and work it step by step to the goal.",
  "Write down the path: each permission/misconfig you abused.",
  "Destroy the scenario with Terraform when done (avoid surprise costs).",
 ],
 "tools": ["CloudGoat", "Your AWS account", "Terraform", "AWS CLI"],
 "resources": R(("CloudGoat", "https://github.com/RhinoSecurityLabs/cloudgoat")),
 "doneWhen": "You completed one CloudGoat scenario and wrote up the attack path.",
 "pitfall": "Forgetting to tear it down — leftover resources can cost money and widen your attack surface.",
},
"P5-07": {
 "overview": "Work an AzureGoat or PurpleCloud scenario — deliberately-vulnerable Azure/Entra environments for safe practice.",
 "steps": [
  "Deploy AzureGoat (or PurpleCloud) into your own lab tenant/subscription.",
  "Work the scenario to its objective, taking notes.",
  "Map what you did to the Entra concepts from P5-01..P5-03.",
  "Tear it down afterward.",
 ],
 "tools": ["AzureGoat / PurpleCloud", "Your Azure subscription", "Terraform"],
 "resources": R(("AzureGoat", "https://github.com/ine-labs/AzureGoat"), ("PurpleCloud", "https://github.com/iknowjason/PurpleCloud")),
 "doneWhen": "You reached the objective in an Azure/Entra goat scenario and documented the path.",
 "pitfall": "Running cloud goats in a production tenant — always a throwaway lab tenant/subscription.",
},
"P5-08": {
 "overview": "Practise a full cloud identity chain: consent-phish -> token -> Graph enumeration -> a privilege path, in a lab tenant. Ties the Entra concepts together.",
 "steps": [
  "In your dev tenant, simulate a consent-phishing app that requests Graph scopes (to yourself).",
  "Use the resulting token to enumerate the tenant via Microsoft Graph.",
  "Find a privilege path (e.g. an over-permissioned app or role).",
  "Document the chain end to end.",
 ],
 "tools": ["Dev tenant", "Microsoft Graph / GraphRunner", "AADInternals (lab)"],
 "resources": R(("GraphRunner", "https://github.com/dafthack/GraphRunner"), ("Microsoft Graph docs", "https://learn.microsoft.com/graph/")),
 "doneWhen": "You went token -> Graph enumeration -> privilege path in your own lab tenant.",
 "pitfall": "Sending a consent prompt to anyone but yourself — keep the phishing simulation inside your tenant.",
},
"P5-09": {
 "overview": "Practise the boundary crossing: compromise on-prem, harvest synced creds / a PRT, and pivot to cloud (and back). The signature hybrid attack.",
 "steps": [
  "In a hybrid lab, start from an on-prem foothold.",
  "Harvest a synced credential or a PRT from a joined machine.",
  "Use it to authenticate to the cloud tenant, then enumerate.",
  "Try the reverse direction too, and diagram both.",
 ],
 "tools": ["Hybrid lab (AD + Entra Connect)", "AADInternals/ROADtools (lab)", "impacket"],
 "resources": R(("ROADtools", "https://github.com/dirkjanm/ROADtools"), ("dirkjanm blog", "https://dirkjanm.io")),
 "doneWhen": "You pivoted on-prem->cloud (or reverse) in a hybrid lab and documented it.",
 "pitfall": "Underestimating the PRT — treat a stolen PRT as cloud game-over and handle it carefully even in lab.",
},
"P5-10": {
 "overview": "The Phase 5 test: own a HYDRID lab (Entra + Connect + on-prem AD) with a boundary-crossing chain in BOTH directions. Proof you understand hybrid attacks.",
 "steps": [
  "Build (or reuse) a full hybrid lab.",
  "Compromise it with a chain that crosses on-prem->cloud AND cloud->on-prem.",
  "Capture evidence and draw both paths.",
  "Write remediation for each crossing.",
 ],
 "tools": ["Full hybrid lab", "ROADtools/AADInternals", "draw.io"],
 "resources": R(("ROADtools", "https://github.com/dirkjanm/ROADtools")),
 "doneWhen": "You demonstrated boundary crossing in both directions in your hybrid lab, with diagrams.",
 "pitfall": "Only proving one direction — the test is that identity flows both ways.",
},
"P5-11": {
 "overview": "Milestone (optional): pass CARTP (Certified Azure Red Team Professional, Altered Security) — the practical Azure/Entra red-team cert.",
 "steps": [
  "Take the CARTP course and complete its Azure lab exercises.",
  "Practise the token/PRT and hybrid attack paths until fluent.",
  "Book and pass the practical exam, then report.",
  "Optional — pursue if cloud/hybrid is your focus.",
 ],
 "tools": ["Altered Security CARTP course + lab"],
 "resources": R(("Altered Security — CARTP", "https://www.alteredsecurity.com/azureadlab")),
 "doneWhen": "You passed CARTP and submitted the report.",
 "pitfall": "Treating cloud as 'the same as on-prem' in the exam — the identity model is genuinely different.",
},
})
# === APPEND ANCHOR ===
